-- Blue Lava shared stories table and policies
-- Run this in Supabase SQL Editor.

create table if not exists public.stories (
  id bigint generated by default as identity primary key,
  nickname text default '',
  is_anonymous boolean not null default true,
  story_text text not null,
  reactions jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.stories enable row level security;

-- Public read policy
drop policy if exists "stories_select_public" on public.stories;
create policy "stories_select_public"
on public.stories
for select
using (true);

-- Public insert policy
drop policy if exists "stories_insert_public" on public.stories;
create policy "stories_insert_public"
on public.stories
for insert
with check (
  char_length(trim(story_text)) > 0
  and char_length(trim(story_text)) <= 3000
  and char_length(coalesce(nickname, '')) <= 80
);

-- Public update policy (only reactions and display fields are expected)
drop policy if exists "stories_update_public" on public.stories;
create policy "stories_update_public"
on public.stories
for update
using (true)
with check (
  char_length(trim(story_text)) > 0
  and char_length(trim(story_text)) <= 3000
  and char_length(coalesce(nickname, '')) <= 80
);

create index if not exists stories_created_at_idx on public.stories (created_at desc);
